# Generated by Django 3.0.6 on 2020-07-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Com',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('employer', models.CharField(max_length=100)),
                ('employeesCount', models.IntegerField()),
                ('medianSalary', models.IntegerField()),
            ],
        ),
    ]
