# Generated by Django 3.0.6 on 2020-07-16 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0002_com'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Com',
        ),
    ]
