# Generated by Django 3.0.6 on 2020-07-16 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0003_delete_com'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employer',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
